# Generated by Django 5.2.3 on 2025-07-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
